base:
  app:
    name: hello-api
    port: 8080

  replicaCount: 1
  environment: stg

  service:
    type: ClusterIP
    port: 8080

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  kargo:
    warehouse:
      enabled: true
      watchPath: argocd/stg/hello-api/values-image.yaml
