apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-{{ .Values.environment }}
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      env: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        env: {{ .Values.environment }}
    spec:
      serviceAccountName: {{ .Values.app.name }}-{{ .Values.environment }}-sa
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
