apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-{{ .Values.environment }}
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.app.port }}
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}
    env: {{ .Values.environment }}
