{{- if .Values.kargo.stage.enabled }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .Values.app.name }}-{{ .Values.environment }}
  namespace: apps
  annotations:
    kargo.akuity.io/description: "{{ .Values.environment | upper }} environment for {{ .Values.app.name }}"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: {{ .Values.app.name }}
    sources:
      {{- if .Values.kargo.stage.directFromWarehouse }}
      direct: true
      {{- else }}
      stages: [{{ .Values.app.name }}-{{ .Values.kargo.stage.sourceStage }}]
      {{- end }}
  promotionTemplate:
    spec:
      steps:
      - task:
          name: {{ .Values.kargo.stage.promotionTemplate }}
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: {{ .Values.app.name }}
        - name: sourceEnv
          value: {{ .Values.kargo.stage.sourceEnv }}
        - name: targetEnv
          value: {{ .Values.environment }}
{{- end }}
