apiVersion: v1
kind: Service
metadata:
  name: hello-api
  labels:
    app: hello-api
    env: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-api
