base:
  app:
    name: hello-api
    port: 8080

  replicaCount: 1

  service:
    type: ClusterIP
    port: 8080

  environment: prod

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
