apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    env: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
