# Nginx STG Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-stg
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: apps:nginx-stg
spec:
  project: default
  source:
    repoURL: https://github.com/dbeilin-playground/config.git
    path: argocd/stg/nginx
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3

---
# Nginx CAND Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-cand
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: apps:nginx-cand
spec:
  project: default
  source:
    repoURL: https://github.com/dbeilin-playground/config.git
    path: argocd/cand/candidate-fra/nginx
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
---
# Nginx PROD Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: apps:nginx-prod
spec:
  project: default
  source:
    repoURL: https://github.com/dbeilin-playground/config.git
    path: argocd/prod/prod-fra/nginx
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3

---
# Hello-API STG Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api-stg
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: apps:hello-api-stg
spec:
  project: default
  source:
    repoURL: https://github.com/dbeilin-playground/config.git
    path: argocd/stg/stg-be/hello-api
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3

---
# Hello-API CAND Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api-cand
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: apps:hello-api-cand
spec:
  project: default
  source:
    repoURL: https://github.com/dbeilin-playground/config.git
    path: argocd/cand/candidate-fra/hello-api
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3

---
# Hello-API PROD Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: apps:hello-api-prod
spec:
  project: default
  source:
    repoURL: https://github.com/dbeilin-playground/config.git
    path: argocd/prod/prod-fra/hello-api
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
