apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: promote-between-envs
spec:
  vars:
  - name: appName      # e.g., "nginx" or "hello-api"
  - name: sourceEnv    # e.g., "stg" or "cand"
  - name: targetEnv    # e.g., "cand" or "prod"
  steps:
  - uses: git-clone
    config:
      repoURL: https://github.com/dbeilin-playground/config.git
      checkout:
      - branch: main
        path: ./config
  - uses: copy
    config:
      inPath: ./config/argocd/${{ vars.sourceEnv }}/${{ vars.appName }}/values-image.yaml
      outPath: ./config/argocd/${{ vars.targetEnv }}/${{ vars.appName }}/values-image.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./config
      message: "🚀 Promote ${{ vars.appName }} ${{ vars.sourceEnv }} → ${{ vars.targetEnv }}"
      author:
        name: "Kargo Bot"
        email: "kargo@apps.com"
  - uses: git-push
    config:
      path: ./config
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.appName }}-${{ vars.targetEnv }}
        namespace: argocd
        sources:
        - repoURL: https://github.com/dbeilin-playground/config.git
