apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: update-nginx-config
spec:
  vars:
  - name: environment      # "stg" or "cand"
  - name: configRepo       # Your config repo URL
  - name: imageRepo        # Your image repo
  
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.configRepo }}
      checkout:
      - branch: main
        path: ./config
  
  - uses: yaml-update
    as: update-image
    config:
      path: ./config/argocd/${{ vars.environment }}/nginx/values-image.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom(vars.imageRepo).Tag }}
  
  - uses: git-commit
    as: commit
    config:
      path: ./config
      message: "🚀 Promote nginx to ${{ vars.environment }}: ${{ imageFrom(vars.imageRepo).Tag }}"
      author:
        name: "Kargo Bot"
        email: "kargo@test.com"
  
  - uses: git-push
    config:
      path: ./config
