# kargo/manifests/stages.yaml
# STG Stages - No promotion steps needed
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-stg
  namespace: apps
  annotations:
    kargo.akuity.io/color: green
    kargo.akuity.io/description: "STG environment for nginx"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      direct: true

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: hello-api-stg
  namespace: apps
  annotations:
    kargo.akuity.io/color: blue
    kargo.akuity.io/description: "STG environment for hello-api"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: hello-api
    sources:
      direct: true

---
# CAND Stages - Use the promotion task
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-cand
  namespace: apps
  annotations:
    kargo.akuity.io/color: yellow
    kargo.akuity.io/description: "CAND environment for nginx"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      stages: [nginx-stg]
  promotionTemplate:
    spec:
      steps:
      - task:
          name: stg-to-cand-promotion
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: nginx
        - name: sourceEnv
          value: stg
        - name: targetEnv
          value: cand

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: hello-api-cand
  namespace: apps
  annotations:
    kargo.akuity.io/color: orange
    kargo.akuity.io/description: "CAND environment for hello-api"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: hello-api
    sources:
      stages: [hello-api-stg]
  promotionTemplate:
    spec:
      steps:
      - task:
          name: stg-to-cand-promotion
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: hello-api
        - name: sourceEnv
          value: stg
        - name: targetEnv
          value: cand
