apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-cand
  namespace: nginx-test
  annotations:
    kargo.akuity.io/color: yellow
    kargo.akuity.io/description: "CAND environment for nginx"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      stages: [nginx-stg]
  promotionTemplate:
    spec:
      steps:
      - task:
          name: update-nginx-config
          kind: ClusterPromotionTask
        vars:
        - name: environment
          value: cand
        - name: configRepo
          value: https://github.com/dbeilin-playground/config.git
        - name: imageRepo
          value: ghcr.io/dbeilin-playground/nginx-app
