# STG Stages - Control Flow (no promotion logic, just receive from warehouses)
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-stg
  namespace: apps
  annotations:
    kargo.akuity.io/color: green
    kargo.akuity.io/description: "STG environment for nginx (reflects current deployed state)"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      direct: true  # Receives freight directly from warehouse

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: hello-api-stg
  namespace: apps
  annotations:
    kargo.akuity.io/color: blue
    kargo.akuity.io/description: "STG environment for hello-api (reflects current deployed state)"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: hello-api
    sources:
      direct: true  # Receives freight directly from warehouse

---
# CAND Stages - Actual Promotion (using reusable PromotionTask)
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-cand
  namespace: apps
  annotations:
    kargo.akuity.io/color: yellow
    kargo.akuity.io/description: "CAND environment for nginx"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      stages: [nginx-stg]  # Takes freight FROM nginx-stg stage
  promotionTemplate:
    spec:
      steps:
      - task:
          name: standard-promotion-pattern
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: nginx
        - name: sourceEnv
          value: stg
        - name: targetEnv
          value: cand

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: hello-api-cand
  namespace: apps
  annotations:
    kargo.akuity.io/color: orange
    kargo.akuity.io/description: "CAND environment for hello-api"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: hello-api
    sources:
      stages: [hello-api-stg]  # Takes freight FROM hello-api-stg stage
  promotionTemplate:
    spec:
      steps:
      - task:
          name: standard-promotion-pattern
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: hello-api
        - name: sourceEnv
          value: stg
        - name: targetEnv
          value: cand
