# CAND Stages - Get freight DIRECTLY from warehouses
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-cand
  namespace: apps
  annotations:
    kargo.akuity.io/color: yellow
    kargo.akuity.io/description: "CAND environment for nginx"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-between-envs
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: nginx
        - name: sourceEnv
          value: stg
        - name: targetEnv
          value: cand

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: hello-api-cand
  namespace: apps
  annotations:
    kargo.akuity.io/color: yellow
    kargo.akuity.io/description: "CAND environment for hello-api"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: hello-api
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-between-envs
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: hello-api
        - name: sourceEnv
          value: stg
        - name: targetEnv
          value: cand

---
# PROD Stages - Get freight from CAND stages
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-prod
  namespace: apps
  annotations:
    kargo.akuity.io/color: red
    kargo.akuity.io/description: "PROD environment for nginx"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      stages: [nginx-cand]  # Get freight from CAND stage
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-between-envs
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: nginx
        - name: sourceEnv
          value: cand
        - name: targetEnv
          value: prod

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: hello-api-prod
  namespace: apps
  annotations:
    kargo.akuity.io/color: red
    kargo.akuity.io/description: "PROD environment for hello-api"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: hello-api
    sources:
      stages: [hello-api-cand]  # Get freight from CAND stage
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-between-envs
          kind: ClusterPromotionTask
        vars:
        - name: appName
          value: hello-api
        - name: sourceEnv
          value: cand
        - name: targetEnv
          value: prod
