app:
  name: nginx
  port: 80

replicaCount: 1

service:
  type: ClusterIP
  port: 80

environment: stg

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
